#! /bin/sh

# formal numerals now
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

background=$(xrdb -query | grep "background" | cut -f2 | sed -r 's/#//' | head -n 1)
foreground=$(xrdb -query | grep "foreground" | cut -f2 | sed -r 's/#//' | head -n 1)
color0=$(xrdb -query | grep "color0" | cut -f2 | sed -r 's/#//' | head -n 1)
color1=$(xrdb -query | grep "color1" | cut -f2 | sed -r 's/#//' | head -n 1)
color2=$(xrdb -query | grep "color2" | cut -f2 | sed -r 's/#//' | head -n 1)
color3=$(xrdb -query | grep "color3" | cut -f2 | sed -r 's/#//' | head -n 1)
color4=$(xrdb -query | grep "color4" | cut -f2 | sed -r 's/#//' | head -n 1)
color5=$(xrdb -query | grep "color5" | cut -f2 | sed -r 's/#//' | head -n 1)
color6=$(xrdb -query | grep "color6" | cut -f2 | sed -r 's/#//' | head -n 1)
color7=$(xrdb -query | grep "color7" | cut -f2 | sed -r 's/#//' | head -n 1)
color8=$(xrdb -query | grep "color8" | cut -f2 | sed -r 's/#//' | head -n 1)

bspc config border_width         4
bspc config window_gap           50
bspc config left_padding	 10
bspc config right_padding	 10
bspc config top_padding		 10
bspc config bottom_padding	 10

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config normal_border_color "#$color8"
bspc config active_border_color "#$color9"
bspc config focused_border_color "#$color9"
bspc config presel_feedback_color "#$color1"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Autostart
#bspwm_colors.sh &
compton &
#wal -i $HOME/wallpapers/lava-with-cherry-tree.-1920×1080.jpg -a 85
wpg --theme $HOME/.config/wpg/schemes/_home_alex__config_wpg_wallpapers_enter-the-unknown-1920×1080_jpg_dark_wal__1.1.0.json --alpha 85
#blurwal -m 1 &
$HOME/.config/polybar/launch.sh
bash "$HOME/.config/bspwm/bspwm_colors.sh" &
